
name: Github Workflow

on: [push]

jobs:
  ...

  # deploy new database schema using dacpac
  build:
      runs-on: ubuntu-latest
      steps:
      # checkout
      - uses: actions/checkout@v1
      # download artifact from azure dev ops
      - name: Download Artifact from Azure Dev Ops
	uses: manishsat/ado-download-artifact@v3
	with:
	  orgName: GagneetChawla0876
	  projectId: demo_tfe
