name: Hello Testing
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build-and-run:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Code
        run: make
      - name: Nominal Run
        run: ./hello
      - uses: actions/upload-artifact@master
        with:
          name: hello-artifact
          path: hello
      - uses: fixpoint/azblob-download-artifact@v3
        with:
          connection-string: DefaultEndpointsProtocol=https;AccountName=brahmleen123;AccountKey=mRWuVVgeUzIHMeiGlFnJ9CFmck/e9KFCQBLRFGde/TqHLMxy7uVO2FkBVIsRI8/lX3KylPMT11exo/GQ0h0L6w==;EndpointSuffix=core.windows.net    

