name: Hello Testing
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build-and-run:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Code
        run: make
      - name: Nominal Run
        run: ./hello
      - uses: actions/upload-artifact@master
        with:
          name: hello-artifact
          path: hello
      - name: Send mail
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: harbrahm
          password: nanakji@486a
          subject: Github Actions job result
          # Literal body:
          body: Build job of ${{github.repository}} completed successfully!
          # Read file contents as body:
          to: harbrahm@gmail.com
          from: harbrahm@gmail.com
          # Optional content type:
          content_type: text/html 
